# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='unpublished_page_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
