# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='id',
        ),
        migrations.AlterField(
            model_name='home',
            name='guid',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
